# Generated by Django 4.0.6 on 2022-07-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fotos')),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.TextField()),
                ('texto_button', models.CharField(max_length=20)),
            ],
        ),
    ]
