# Generated by Django 4.0.6 on 2022-07-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=12, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='depoimentos', verbose_name='Imagem Depoimentos')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo Depoimentos')),
                ('cliente', models.CharField(max_length=250, verbose_name='Nome Cliente')),
                ('ocupcliente', models.CharField(max_length=20, verbose_name='Ocupacao Cliente')),
                ('depoimento', models.TextField(verbose_name='Depoimento')),
            ],
        ),
        migrations.CreateModel(
            name='FormContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome Form')),
                ('telefone', models.CharField(max_length=12, verbose_name='Telefone Form')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Form')),
                ('mensagem', models.TextField(max_length=400, verbose_name='Mensagem Form')),
                ('textbutton', models.CharField(max_length=20, verbose_name='Texto Button')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portifolio', verbose_name='Imagem Portifolio')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo Portifolio')),
                ('subtitulo', models.CharField(max_length=250, verbose_name='Subtitulo Portifolio')),
                ('descricao', models.TextField(verbose_name='Descricao Portifolio')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='servicos', verbose_name='Imagem Servicos')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo Servicos')),
                ('subtitulo', models.CharField(max_length=250, verbose_name='Subtitulo Servicos')),
                ('descricao', models.TextField(verbose_name='Descricao Servicos')),
            ],
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sobre', verbose_name='Imagem Sobre')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo Sobre')),
                ('descicao', models.TextField(verbose_name='Descricao Sobre')),
            ],
        ),
        migrations.AlterField(
            model_name='inicio',
            name='descricao',
            field=models.TextField(verbose_name='Descricao do Inicio'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='image',
            field=models.ImageField(upload_to='fotos', verbose_name='Imagem Inicio'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='Titulo Inicio'),
        ),
    ]
