# Generated by Django 4.0.6 on 2022-07-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0002_contato_depoimentos_formcontato_portfolio_servicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
