# Generated by Django 4.0.6 on 2022-07-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0003_contato_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=15)),
                ('facebook', models.CharField(max_length=15)),
                ('youtube', models.CharField(max_length=15)),
            ],
        ),
    ]
